insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'heuristic', 'encoding', 166, 38, 2, 73);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'attitude', 'Multi-layered', 106, 15, 15, 60);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'algorithm', 'Organic', 154, 5, 36, 97);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Programmable', 'Inverse', 37, 49, 15, 14);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Reduced', 'secondary', 44, 28, 50, 8);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Profound', 'core', 80, 3, 14, 79);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'firmware', 'Expanded', 141, 39, 32, 54);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Team-oriented', 'productivity', 168, 9, 48, 95);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Switchable', '4th generation', 46, 15, 22, 44);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Adaptive', 'well-modulated', 156, 6, 8, 59);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Streamlined', 'fault-tolerant', 95, 39, 39, 9);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'discrete', 'executive', 154, 28, 22, 2);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Persevering', 'Mandatory', 137, 2, 33, 29);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Focused', '24 hour', 68, 46, 8, 48);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Self-enabling', 'Universal', 38, 29, 24, 83);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'dynamic', 'software', 69, 36, 14, 89);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'tertiary', 'middleware', 126, 45, 15, 100);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'fault-tolerant', '3rd generation', 75, 25, 44, 84);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'parallelism', 'optimal', 154, 19, 11, 49);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'static', 'Up-sized', 77, 25, 21, 65);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Optimized', 'User-friendly', 111, 13, 34, 51);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Reverse-engineered', 'full-range', 65, 50, 40, 75);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Synergistic', 'extranet', 20, 50, 21, 62);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'empowering', 'hub', 20, 28, 43, 34);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'software', 'process improvement', 126, 18, 45, 91);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'capacity', 'forecast', 61, 22, 12, 27);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Quality-focused', 'User-centric', 86, 48, 39, 48);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Pre-emptive', 'context-sensitive', 62, 44, 38, 22);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'budgetary management', 'hardware', 144, 22, 17, 43);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'multimedia', 'content-based', 26, 23, 38, 22);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'synergy', 'contextually-based', 60, 38, 43, 57);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Upgradable', 'standardization', 60, 15, 42, 76);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'emulation', 'process improvement', 25, 37, 21, 52);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'application', 'knowledge base', 87, 19, 37, 16);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Fully-configurable', 'stable', 104, 34, 6, 8);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'clear-thinking', 'Advanced', 45, 27, 35, 15);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'transitional', 'cohesive', 170, 24, 44, 54);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'service-desk', 'object-oriented', 38, 42, 41, 79);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'empowering', 'responsive', 129, 8, 4, 3);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'encryption', 'Customizable', 57, 16, 45, 61);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'high-level', 'Virtual', 168, 11, 8, 85);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'background', 'optimizing', 134, 31, 29, 27);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'artificial intelligence', 'Innovative', 129, 40, 47, 22);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Cross-group', 'Cloned', 81, 7, 20, 17);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'content-based', 'Realigned', 51, 29, 21, 81);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'structure', 'throughput', 59, 7, 41, 39);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Cross-group', 'internet solution', 75, 38, 1, 87);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Versatile', 'client-server', 108, 35, 8, 38);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Multi-tiered', 'Reactive', 26, 11, 10, 43);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Assimilated', 'upward-trending', 112, 28, 20, 50);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Integrated', 'Managed', 90, 23, 19, 90);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'dynamic', 'Diverse', 85, 49, 40, 12);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'internet solution', 'Open-source', 156, 47, 31, 37);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'object-oriented', 'content-based', 30, 9, 37, 50);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'system-worthy', 'Programmable', 38, 36, 21, 72);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Face to face', 'holistic', 21, 13, 35, 44);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Open-architected', 'standardization', 87, 21, 49, 48);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Sharable', 'Reduced', 99, 43, 29, 39);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'analyzing', 'Progressive', 124, 36, 4, 64);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Proactive', 'Reactive', 33, 12, 48, 65);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'initiative', 'optimal', 62, 15, 41, 84);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'empowering', '5th generation', 29, 28, 17, 88);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'ability', 'flexibility', 65, 42, 37, 37);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'hierarchy', 'contextually-based', 41, 31, 14, 76);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'encryption', 'Horizontal', 180, 5, 24, 15);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'cohesive', 'web-enabled', 102, 34, 13, 94);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Networked', 'Distributed', 48, 26, 15, 90);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'value-added', 'Optional', 141, 36, 27, 86);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, '6th generation', 'frame', 33, 45, 31, 8);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'flexibility', 'pricing structure', 78, 4, 38, 51);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'utilisation', '3rd generation', 74, 38, 27, 7);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Inverse', 'model', 163, 7, 46, 13);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Phased', 'structure', 84, 47, 16, 25);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'discrete', 'Decentralized', 105, 43, 1, 50);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Implemented', 'Up-sized', 28, 22, 40, 4);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Sharable', 'array', 112, 7, 3, 27);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Digitized', 'leverage', 29, 43, 19, 29);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, '5th generation', 'migration', 44, 20, 34, 1);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'explicit', 'methodology', 96, 31, 14, 41);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Face to face', 'Reduced', 41, 44, 14, 86);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'website', 'Organic', 113, 21, 42, 24);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'function', 'data-warehouse', 170, 35, 23, 46);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'multi-tasking', 'mission-critical', 128, 50, 12, 87);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'architecture', 'clear-thinking', 133, 13, 9, 70);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'standardization', 'stable', 66, 1, 9, 42);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'fault-tolerant', 'Optional', 43, 39, 42, 56);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'next generation', 'logistical', 25, 12, 33, 91);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'structure', 'customer loyalty', 26, 11, 43, 61);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'neural-net', 'help-desk', 164, 42, 33, 62);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'well-modulated', 'Graphic Interface', 125, 6, 32, 35);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Synergized', 'Object-based', 143, 38, 22, 72);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Decentralized', 'content-based', 163, 2, 14, 55);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Innovative', 'Compatible', 67, 41, 21, 27);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'national', 'artificial intelligence', 82, 43, 38, 80);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'executive', 'Enhanced', 100, 29, 8, 57);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'framework', 'heuristic', 97, 2, 29, 87);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'projection', 'Visionary', 75, 9, 40, 23);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'concept', 'Compatible', 32, 17, 12, 100);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Versatile', 'leverage', 90, 42, 24, 95);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Reduced', 'Organized', 124, 25, 46, 44);
