insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'portal', 'mobile', 73, 29, 17, 16);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'moderator', 'leading edge', 89, 33, 11, 3);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'portal', 'policy', 162, 6, 21, 42);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Future-proofed', 'contingency', 71, 14, 4, 60);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Innovative', 'Right-sized', 108, 3, 47, 53);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Face to face', 'mission-critical', 39, 39, 5, 93);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'open architecture', 'concept', 148, 25, 38, 3);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'multi-state', 'fresh-thinking', 133, 39, 32, 74);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'clear-thinking', 'dynamic', 113, 8, 39, 98);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'help-desk', 'algorithm', 150, 41, 9, 88);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'attitude', 'regional', 144, 7, 13, 4);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Intuitive', 'Extended', 83, 48, 30, 73);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'responsive', 'local area network', 83, 34, 38, 90);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'productivity', 'Up-sized', 107, 24, 25, 23);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'system-worthy', 'Organized', 50, 4, 26, 47);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'support', 'Fundamental', 168, 25, 28, 78);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'local', 'Synergized', 62, 17, 15, 3);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'explicit', 'middleware', 162, 37, 2, 67);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Cloned', 'projection', 164, 22, 20, 69);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'disintermediate', 'attitude-oriented', 160, 18, 10, 35);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'eco-centric', 'Decentralized', 30, 10, 36, 10);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Optional', 'Fully-configurable', 158, 32, 2, 51);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'help-desk', 'Synergistic', 127, 32, 20, 56);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Centralized', 'Streamlined', 53, 48, 37, 70);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'paradigm', '24/7', 40, 38, 7, 60);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'synergy', 'asynchronous', 142, 1, 7, 19);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'executive', 'Open-source', 92, 7, 48, 3);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'customer loyalty', 'archive', 106, 34, 45, 47);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'success', 'Business-focused', 73, 15, 29, 81);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'local', 'paradigm', 85, 18, 44, 25);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Diverse', 'Organic', 30, 8, 43, 5);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'bi-directional', 'Devolved', 109, 20, 23, 5);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'human-resource', 'Reverse-engineered', 175, 7, 23, 47);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'coherent', 'foreground', 107, 25, 46, 93);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'system-worthy', 'framework', 82, 44, 28, 26);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Multi-channelled', 'even-keeled', 168, 43, 4, 4);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'well-modulated', 'regional', 153, 25, 13, 34);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'encompassing', 'strategy', 114, 44, 42, 58);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'secured line', 'attitude-oriented', 54, 43, 21, 72);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Devolved', 'info-mediaries', 41, 35, 20, 60);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Object-based', '24 hour', 32, 41, 38, 27);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'conglomeration', 'time-frame', 178, 50, 31, 77);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'attitude', 'eco-centric', 102, 10, 34, 1);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'web-enabled', 'Secured', 92, 45, 36, 88);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Reduced', 'hybrid', 74, 49, 10, 46);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Reactive', 'array', 86, 28, 46, 63);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'middleware', 'Operative', 27, 27, 35, 18);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'access', 'Reactive', 76, 39, 18, 14);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, '24 hour', 'installation', 65, 23, 10, 35);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'client-server', 'Operative', 157, 14, 42, 26);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'composite', '6th generation', 61, 40, 32, 68);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'bifurcated', 'Synchronised', 140, 11, 19, 52);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'productivity', 'website', 124, 36, 21, 60);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'methodology', 'Programmable', 120, 6, 17, 63);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Enterprise-wide', 'Distributed', 140, 28, 38, 46);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'exuding', 'dedicated', 174, 27, 41, 8);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Ameliorated', 'real-time', 90, 47, 40, 39);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Synergized', 'even-keeled', 117, 46, 3, 31);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Optional', 'encoding', 70, 49, 50, 88);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'secondary', 'directional', 23, 18, 30, 50);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'access', 'Self-enabling', 172, 31, 23, 9);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'content-based', 'analyzing', 156, 38, 50, 62);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'service-desk', 'secured line', 177, 45, 40, 6);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'challenge', 'Advanced', 109, 43, 27, 8);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'intangible', 'Phased', 105, 11, 3, 85);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'product', 'pricing structure', 124, 11, 42, 63);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Mandatory', 'mobile', 86, 50, 42, 35);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'background', 'Exclusive', 106, 18, 39, 85);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Configurable', 'framework', 28, 31, 34, 57);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'challenge', 'Synergized', 77, 3, 24, 64);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'directional', 'Upgradable', 104, 46, 46, 52);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'initiative', 'fault-tolerant', 54, 20, 28, 46);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Centralized', 'maximized', 43, 27, 4, 89);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'info-mediaries', 'Pre-emptive', 41, 47, 24, 1);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'optimizing', 'Synergistic', 109, 45, 46, 50);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'content-based', 'User-friendly', 140, 23, 17, 68);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'portal', 'intangible', 127, 8, 13, 31);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'parallelism', 'protocol', 57, 33, 4, 33);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'contingency', 'function', 75, 16, 42, 41);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Automated', 'Diverse', 23, 41, 17, 100);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Up-sized', 'throughput', 155, 13, 45, 73);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'demand-driven', 'archive', 21, 20, 22, 97);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Digitized', 'capability', 90, 14, 37, 88);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'intangible', 'holistic', 175, 4, 27, 12);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Integrated', 'zero tolerance', 64, 23, 3, 12);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Exclusive', 'portal', 160, 17, 14, 33);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'User-friendly', 'success', 107, 35, 25, 36);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'project', 'zero administration', 65, 47, 18, 92);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'user-facing', 'Open-source', 85, 4, 44, 70);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Visionary', 'Distributed', 105, 30, 38, 3);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Multi-layered', 'Front-line', 76, 45, 33, 79);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Persistent', 'ability', 103, 43, 42, 98);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Multi-layered', 'Secured', 48, 37, 30, 6);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'radical', 'leading edge', 130, 48, 42, 83);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'Programmable', 'Switchable', 145, 3, 22, 59);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'implementation', 'Ameliorated', 78, 40, 25, 49);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'tertiary', 'time-frame', 172, 13, 24, 31);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'upward-trending', 'Fully-configurable', 117, 48, 2, 60);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'artificial intelligence', 'Monitored', 108, 28, 7, 83);
insert into result (id, description, goal, workload, reps, sets, connected_exercise_id) values (null, 'executive', 'incremental', 30, 41, 27, 73);
